language: python
python:
  - "3.8.9"

# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --noinput --settings silkscreenservice.settings_test