# Generated by Django 3.2.6 on 2021-11-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artwork',
            field=models.FileField(blank=True, null=True, upload_to='artwork/%Y/%m/%d'),
        ),
    ]
