# Generated by Django 3.2.6 on 2021-09-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210925_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingmethod',
            name='method',
            field=models.CharField(choices=[('one_sided', '4/0 CMYK'), ('double_sided', '4/4 CMYK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='method',
            field=models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('a6', 'A6'), ('a0', 'A0'), ('a1', 'A1'), ('a2', 'A2'), ('standard', 'Standard'), ('double_v', 'Double V'), ('double_h', 'Double H')], max_length=50),
        ),
    ]
