# Generated by Django 3.2.6 on 2021-09-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_producttag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
